provider "aws" {

  region     = "us-east-1"
  access_key = "ASIA5OAWNTOSRYWAD5VB"
  secret_key = "7NWKWKGLy1Upj36NzeJZRHjhrlv3IyXcTjDRZWfB"
  token = ""
}

variable "generated_key_name" {
  type        = string
  default     = "terraform-key-pair"
  description = "Key-pair generated by Terraform"
}

resource "tls_private_key" "dev_key" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "generated_key" {
  key_name   = var.generated_key_name
  public_key = tls_private_key.dev_key.public_key_openssh

  provisioner "local-exec" {    # Generate "terraform-key-pair.pem"
    command = "echo '${tls_private_key.dev_key.private_key_pem}' > ./'${var.generated_key_name}'.pem"
  }

  provisioner "local-exec" {
    command = "chmod 400 ./'${var.generated_key_name}'.pem"
  }
}

resource "aws_instance" "Jenkins" {
  ami           = "ami-0c4f7023847b90238"
  instance_type = "t2.micro"
  key_name      = aws_key_pair.generated_key.key_name
}
