variable "aws_region" {
   description = "AWS Region to launch servers"
   default = "us-east-1"
}

variable "aws_access_key" {
   description = "AWS User Access Key"
   default = "ASIA5OAWNTOSZP67T66B"
}

variable "aws_secret_key" {
   description = "AWS User Secret Key"
   default = "VFpDrVRxtWy9S9CHkOY4yVAgOb4oxnLjkCg5ZJlw"
}

variable "aws_api_token" {
   description = "AWS API Token"
   default = "FwoGZXIvYXdzEIb//////////wEaDIYpFDCH6FbeRbvvESK1Ae+9z4t5RIMeO94mVc7aONMcl8EYb9yZZgEtw3iJCWNW8lbT4DMNHVy6phCJmtzZUqJS0UhjYpbSqp+TR0vF0q4uNRuozIxmnAo/BiS3iAKTsttm1cI7bByheo7j60q9vshFNPQpfrP50ER3vFyA72al/Dk4jri0LpohDmUfgh7mAeI0xP6jFG2obmUdUffBVCrQ6221jj7hYUB7ZZFtlZ4SojyUEgBuZdW7QtmmxtWFoVu2x9Io1Ov1kwYyLW8CQW7Db87nO8PyycsorpYKEdqdlDPqjQNS/R1RwCm/2Q2j+eCDTZ99e25CjA=="
}

variable "aws_amis" {
   default = {
       us-east-1 = "ami-09d56f8956ab235b3"
       eu-west-2 = "ami-0ee8244746ec5d6d4"
   }
}

variable "instance_type" {
   description = "Type of AWS EC2 instance."
   default     = "t2.micro"
}

variable "generated_key_name" {
  type        = string
  default     = "tf-key-pair"
  description = "Key-pair generated by Terraform"
}

variable "instance_count" {
   default = 1
}
